### ISSUE TITLE
'--score all' option adds only a single value

### ISSUE THREAD

**Issue by sudarshanchari** [LiuLabUB/HMMRATAC#12]
Hi,

I am trying to run HMMRATAC v1.2.3 with the following options
```
java -jar HMMRATAC_V1.0_exe.jar
-b file.bam
-i file.bai
-g genomefile.txt
-w file.bigwig
--bedgraph true
--bgscore true
--score all
-o file_hmmratac
```

According to the guide the ```--score all``` option should produce all types of scores separated by an 'underscore'. But I get only the default score in the relevant output. Just wondering if I am misunderstanding the score option or if this is a bug. Please let me know when you get a chance.

Thank you!

**Comment by EvanTarbell** [comment]
Thanks for the comment. It turns out that it is a bug. I'll correct it and release a new version. I'll have it out ASAP.

**Comment by EvanTarbell** [comment]
Version 1.2.4 should take care of this. Let me know if it works

**Comment by sudarshanchari** [comment]
The output contains different scores separated by '_' So I think this works now.

Thank you!

**Comment by EvanTarbell** [comment]
I updated the Guide to list the order of the "all" option as well. The order is 
MAX_MEAN_MEDIAN_ZSCORE_FOLDCHANGE

**Comment by sudarshanchari** [comment]
Perfect! Thank you!
