### ISSUE TITLE
HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:636

### ISSUE THREAD

**Issue by KeyTals** [LiuLabUB/HMMRATAC#13]
I am getting the "HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:636" for all the samples.

Here is the command.

java -Xmx8g -jar HMMRATAC/HMMRATAC_V1.2.4_exe.jar -b sorted.bam -i sorted.bam.bai -g genome.info -e blacklist.bed -o out.file

It does create log and model file.

Here is the tail of log file
181 round viterbi done
182 round viterbi done
183 round viterbi done
184 round viterbi done
185 round viterbi done

Keyur

**Comment by EvanTarbell** [comment]
Can you post the entire error message, along with the first ~60 lines of the log file (however many lines it takes to display the entire model parameters, both the initial and final models)?

Thanks

**Comment by KeyTals** [comment]
[N_ATAC.log](https://github.com/LiuLabUB/HMMRATAC/files/3054640/N_ATAC.log)

I have attached the log file, It created just one model file.

Keyur

**Comment by KeyTals** [comment]
Error file has only two lines 

Exception in thread "main" java.lang.NullPointerException
	at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:636)

Keyur

**Comment by EvanTarbell** [comment]
Thanks.  It looks like a bug in the code when adding back high coverage regions to the peak file. I can correct that and publish a new release soon. 
One question, did a XXX_peaks.gappedPeak file get created? It should have been created and should contain all the HMMRATAC peaks.  The only thing that would be missing are the excluded regions (the blacklist regions and any regions that are "high coverage" - typically artifacts).  
One side note, the --peaks option is a boolean for determining if a peak file should be created. The options are either "True" or "False". If no peak file was created, leave out this option and it should be.  
The peak file should be correct. You can use it while i work on fixing the bug.

**Comment by KeyTals** [comment]
No peak file was not generated. I did run "--peaks 200" but leave out from the commands above as it is default option. Do  i need to set something else along with it to generate peak file?

Also i dint adjust the reads start site in bam file for Tn5 transposase. Do i need to do this step before i use the bam file for peak calling? Currently i am using sorted bam file.

Keyur

**Comment by EvanTarbell** [comment]
"--peaks 200" is not a valid option. -p or --peaks is for determining whether or not a peak file should be created. The only values that can be used are "True" or "False".  therefore the way to report a peak file would be "--peaks True" (no quotes).  

And no, you dont need to adjust the start sites in the bam file.  We find that for peak calling, it isnt necessary. For other tasks, such as TF footprinting, it would be important, but for the resolution of peak calls, it wont affect much.

**Comment by EvanTarbell** [comment]
version 1.2.5 should fix this issue
