### ISSUE TITLE
Can HMMRATAC be set to use multiple threads?

### ISSUE THREAD

**Issue by daramirez** [LiuLabUB/HMMRATAC#14]
Hi,
Can HMMRATAC be set to run using multiple threads? I could not find any indication of this from the documentation.
Or could I just set it through java itself with something like the following?
java -XX:ParallelGCThreads=<num_of _threads> -jar HMMRATAC_V1.2.4_exe.jar

**Comment by EvanTarbell** [comment]
Hi,
No, HMMRATAC does not currently have the ability to run using multiple threads.  It is a feature that we plan to add in the future.
