### ISSUE TITLE
illegal output format

### ISSUE THREAD

**Issue by balwierz** [LiuLabUB/HMMRATAC#16]
I got this line in the gappedPeak output:
`chr13   51779070        51780230        Peak_298118     .       .       51779600        51780230        255,0,0 3       1,630,1    0,530,1159`

Note that 630+530 = 1160. Blocks are overlapping.
Why are there these flanking 1-bp blocks anyway?

**Comment by EvanTarbell** [comment]
Thanks for the comment. I'll work on correcting that issue for later releases. For the record, the flanking 1bp blocks were made for visualization only, so as to make the center portion be displayed as a solid block in a browser.  The entire peak is represented by the main coordinates and the _center_ state are represented by the other set of coordinates (ie 51779600-51780230).
