### ISSUE TITLE
Hard-coded duplicate removal

### ISSUE THREAD

**Issue by plantformatics** [LiuLabUB/HMMRATAC#18]
Duplicate removal prior to peak calling makes perfect sense when calling peaks on tissue-level ATAC-seq experiments. However, single-cell experiments can retain identical fragments derived from different cells. Thus, I am curious if future releases will be sensitive to this characteristic of single cell ATAC-seq data?

**Comment by EvanTarbell** [comment]
That is an excellent point! I will release a new version where duplicate removal is no longer hard-coded and is instead an option settable at runtime.

**Comment by plantformatics** [comment]
That would be fantastic! Thanks for the quick response.

**Comment by EvanTarbell** [comment]
Version 1.2.6 should take care of this issue now. Thanks

**Comment by hmyh1202** [comment]
nice  ！
