### ISSUE TITLE
How to find the four chromatin states from output files?

### ISSUE THREAD

**Issue by kyliao** [LiuLabUB/HMMRATAC#2]
Hi,
HMMRATAC identifies a set of training regions throughout the genome to train a 4-states Hidden Markov Model (HMM) with multivariate Gaussian emissions, representing the underlying four chromatin states of 1) the center of open chromatin, 2) the flanking regions, 3) the non-flanking regions and 4) the background.I used HMMRATAC by default  parameters,but the output file( Name_peaks.gappedPeak ) just indicate score of standard peaks and standard peaks with the position of flanking nucleosome and open state , not include four chromatin states .And could HMMRATAC output the score of nucleosome to measure nucleosome occupancy？
Hope your replay，thanks .

**Comment by EvanTarbell** [comment]
Yes it is possible to get the state annotation for every genomic position. Set the --bedgraph option to true. This will report a genome-wide bedgraph file, where every genomic position is annotated as one of the four states.  To get a score for each position, set the --bgscore option to true. This will make the bedgraph contain an additional column that will have the score of each annotation.  Please note that this will add considerable time to the program.  One way to decrease time is to set the -f option to false. This will stop HMMRATAC from doing the fragment length training. If HMMRATAC has already been run, then the log file will contain the values of the EM fragment training.  You can set the values for the means and standard deviations for the new HMMRATAC run with the -m and -s options. This way, HMMRATAC will use the correct values that were already determined, without wasting the time to run the EM again.

**Comment by kyliao** [comment]
First,thanks for your replay！
I have tried to set --bedgraph option and --bgscore option to true，but the Name.bedgraph only include four colnames .

**Comment by EvanTarbell** [comment]
No, in most cases, E0 means the background state. E1 is the non-flanking nucleosome, E2 is the flanking nucleosome and E3 is the open region. Also, it appears that i found a small bug in the code. Whereas most true/false statements are case insensitive, the --bgscore option isnt. Try putting in --bgscore true (lowercase). This should work. I will be updating the code soon to fix this problem in the future. And thank you for bringing it to my attention!!

**Comment by kyliao** [comment]
I try putting in --bgscore true (lowercase) and it worked .Every score of  each annotation means read coverage of this region？

**Comment by EvanTarbell** [comment]
Yes, it means the _maximum_ read coverage across that region.

**Comment by kyliao** [comment]
Thank you very much for your answer.
