### ISSUE TITLE
Replicate handling

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [LiuLabUB/HMMRATAC#20]
In the paper (HMMRATAC: a Hidden Markov ModeleR for ATAC-seq) I see you just merge the fastq files for the replicates. Is this the recommended way of doing it? Or is there a more 'sophisticated' way?

**Comment by EvanTarbell** [comment]
That is a great question.  There are several ways to handle replicates with HMMRATAC.  The simplest is to merge the replicates and run HMMRATAC on the merged file.  Alternatively, you could run HMMRATAC on each replicate and then run IDR or some other tool to determine reproducible peaks.  We haven't tested different replicate strategies so I can't say definitively which approach is best.

**Comment by Maarten-vd-Sande** [comment]
So if we want to use IDR we should convert the gappedpeak into narrowpeak(ish)? I am not that familiar with either data type, but the p-values are interchangeable between data types?

**Comment by EvanTarbell** [comment]
That isn't necessary. You can specify at runtime what column IDR should use for the "score".  We report the score as column 13.  The thing to keep in mind is whether IDR considers high scores to be better (which applies to HMMRATAC's scoring systems) or whether lower scores are better (in the case of a peak callers that report raw p-values).  I don't remember what the default is for IDR. 
 
I should also point out that HMMRATAC doesn't report a p-value. The default scoring system for HMMRATAC is the maximum number of reads mapping to a peak. Other options include the mean number of reads, the median number of reads, the fold change over genomic background and the z-score compared to genomic background.  See --score option for more details.  In each case, however, the higher the score the more confident the peak (hence my above comment).

**Comment by Maarten-vd-Sande** [comment]
Thanks a lot, that is useful info!

**Comment by celinajose** [comment]
Dear Evan,
I've noticed that IDR considers low scores to be better, as mentioned above.
Do you think this would be a problem to run IDR in HMMRATAC gappedpeak files?
Or do you recommend merging the fastqs, or the bams?

Thank you in advance.

**Comment by EvanTarbell** [comment]
It isn't a problem running IDR with the gappedPeak files, you just have to specify which column is the score (for HMMRATAC it is column 13) and you have to specify that the higher the score the better the call (i dont remember how but there is a way to do that with IDR).

**Comment by celinasjose** [comment]
Thank you for your help.
