### ISSUE TITLE
How to define Open Chromatin Regions?

### ISSUE THREAD

**Issue by xpan1** [LiuLabUB/HMMRATAC#25]
My purpose is to use the open chromatin regions to do MEME analysis to get the potential motif in the open chromatin regions, in this way, which column I should use in the Name_peaks.gappedPeak
? Is the peak start and peak end columns, or the Open state start and end columns? Thanks!

**Comment by EvanTarbell** [comment]
For motif analysis, I'd actually recommend using the summits defined in the Name_summits.bed file.  We showed in our paper that these sites are the most likely locations of TF binding, as defined by the enrichment in PhastCons scores (vertebrate conservation - a hallmark, though no requirement, of TF binding).  In fact, any time you're doing motif analysis with ATAC-seq, you should use the summits, even with other algorithms (ie MACS2).
