### ISSUE TITLE
Add CPM normalization to track signals

### ISSUE THREAD

**Issue by EvanTarbell** [LiuLabUB/HMMRATAC#27]
Add cpm normalization to signal tracks. Will help with consistency between samples (at similar settings) and will allow data sets to be run using master models, rather than needing one for every data set.

**Comment by xpan1** [comment]
Which parameter to use to do CPM normalization?

**Comment by EvanTarbell** [comment]
This hasn't been implemented yet.  I will add the normalization to the tracks and release another version soon.

**Comment by EvanTarbell** [comment]
Release 1.2.8 implements this

**Comment by xpan1** [comment]
To make sure the right way to do the CPM normalization, is it included in the HMMRATAC R package directly, rather than adding parameters to proceed normalization, is that correct?

**Comment by EvanTarbell** [comment]
HMMRATAC now calculates the scaling factor as such:
It counts the number of fragments in the BAM file
It divides that number by 1 million
It divides the signal tracks by the resulting scaling factor.

This should make runs with different samples more comparable by normalizing by fragment depth.

The user doesn't have to do anything. It all happens automatically.
