### ISSUE TITLE
If my data quality is not good, do this software can still be used to identify open chromatin regions?

### ISSUE THREAD

**Issue by xpan1** [LiuLabUB/HMMRATAC#28]
Quality control of ATAC-Seq data showed that one of samples showed bad qualities, since this method is based on machine learning (self-study process), I was wondering whether HMMRATAC can be used to detect open chromatin regions for this poor-quality data

**Comment by EvanTarbell** [comment]
It depends. As with all software, bad data will give a bad result.  
Having said that, the most important consideration for HMMRATAC (and should be for all ATAC-seq data sets) is the multimodal fragment length distribution that the original authors identified.  As long as you see that, you could run it.  But i would be careful in what you do with it and what you interpret from it. But that goes for any algorithm.
