### ISSUE TITLE
Are the ATACseq data with fragment distribution of NFRs, 1Ns, and (slightly) 2Ns suitable for HMMRATAC

### ISSUE THREAD

**Issue by imst0715** [LiuLabUB/HMMRATAC#31]
I am wondering whether my data belong to the proper data with multi-peak distribution of fragment length, mentioned at #28 since the peaks of >1N are not clear or even not there. 
![Fragment length](https://user-images.githubusercontent.com/11597166/65815892-871df480-e227-11e9-8b54-c7227ed24bbf.png)
 
Do you think my data are suitable for HMMRATAC? The species is budding yeast with the genome size of 12M bp. We sequenced with 10M reads (2x150bp)/5K cells. The distribution shown here are from 3 repeats. That is 30 M reads.

Another unrelated question is what the sharp peak of 150bp could be.

Thank you.

**Comment by EvanTarbell** [comment]
That looks fine to use HMMRATAC.  It is possible to remove some of the signal tracks that HMMRATAC uses, in the event that your data has fewer larger reads. For instance, to remove the "3N" track, you would set --trim to 1 (ie. remove one of the separated signals). Setting --trim to 2 would remove the 3N and 2N track (two of the separated signals), leaving only the NFR and 1N. With your data, i'd recommend using --trim 1 to start.
