### ISSUE TITLE
How can I have the data of NFRs and 1Ns to create the heatmap shown in Fig. 2B of your NAR paper?

### ISSUE THREAD

**Issue by imst0715** [LiuLabUB/HMMRATAC#32]
We are planing to analyze our data with HMMRATAC to investigate whether nucleososome changes in mutants for chromatin remodeling complex and related genes. To have more comprehensive understanding, we would like to examine the heapmap of the NFRs and 1Ns. Therefore, I am wondering how I could output the needed data generated by HMMRATAC. 

Thank you.

**Comment by EvanTarbell** [comment]
If you want ALL center states and 1N nucleosome states throughout the genome, you can set the 
--bedgraph true. This will output a bedgraph file of the whole genome and every annotation. The center (NFR) state is E2 and the nucleosome state is E1. Alternatively, if you want only those center and nucleosome states around annotated peaks (those that pass the various tests post-annotation), you can use the gappedPeak file. The coordinates represent the center state and the flanking nucleosomes. If you pull out the coordinates at columns 7 and 8, these are the start and stops of the center state. Subtracting them from the coordinates at columns 2 and 3 (ie with bedtools subtract) leave you with the flanking nucleosomes.

**Comment by imst0715** [comment]
Thank you for your reply. I may have some related questions after discussing with my lab members. Could you wait for a while and not to close this tread?

**Comment by imst0715** [comment]
Thank you for your waiting, EvanTarbell. I don't have related questions.
