### ISSUE TITLE
download HMMRATAC always error and slowly

### ISSUE THREAD

**Issue by qiaowei-vvjoe** [LiuLabUB/HMMRATAC#33]
Hi dear developers,
Thank you so much for developing. 
I use centos and the java version is 
```
$ java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)```
I download it 
```
$ nohup wget https://github.com/LiuLabUB/HMMRATAC/releases/download/1.2.9/HMMRATAC_V1.2.9_exe.jar &```
but it really strange that I tried HMMRATAC_V1.2.9_exe.jar/HMMRATAC_V1.2.8_exe.jar/HMMRATAC_V1.2.7_exe.jar it always error and very very slowly.Attachment is my nohup.out file.I am not good at java and I really don't know if it is just because my slow Internet speed.Could you please give me some advice about this stupid question?Thank you so much in advance.
[nohup.log](https://github.com/LiuLabUB/HMMRATAC/files/3686554/nohup.log)

**Comment by EvanTarbell** [comment]
It seems to be related to your internet speed. Some of the entries say that downloading will take 14hours. I just downloaded it onto my computer to test and it took half a minute.  I assume that you are trying to download it onto a server? Could you download it onto your computer and then use scp to transfer it onto the server? The file isn't that large. It seems strange that a server couldn't handle it.

**Comment by qiaowei-vvjoe** [comment]
yes.
@EvanTarbell 
It's really strange.
I tried to download onto a server always shows error like.
`Read error at byte 1113669/30317270 (Connection reset by peer).`
and I also tried download onto my local computer it always show 0B with no progress.
Well...so I think I should know something about `(Connection reset by peer)`I have never met this error when wget.

**Comment by qiaowei-vvjoe** [comment]
Hi
@EvanTarbell 
I restarted my network switch and it finally succeed with only less than half an hour.
Now I am testing samples.
I close this issue.
Any other questions I will restart another one.
