### ISSUE TITLE
State3_regions.bed is 0 means no open region and my data quality is poor?

### ISSUE THREAD

**Issue by qiaowei-vvjoe** [LiuLabUB/HMMRATAC#34]
Hi I ran HMMRATAC in `openjdk version "1.8.0_191"`  with attachment of log file.
[As.log](https://github.com/LiuLabUB/HMMRATAC/files/3694443/As.log)

I have known from https://github.com/LiuLabUB/HMMRATAC/issues/2 which you said 

```in most cases, E0 means the background state. E1 is the non-flanking nucleosome, E2 is the flanking nucleosome and E3 is the open region in the bedgraph file.```

so I grep the 4 files 
```
grep E0 As.bedgraph > As.State0_regions.bed
grep E1 As.bedgraph > As.State1_regions.bed
grep E2 As.bedgraph > As.State2_regions.bed
grep E3 As.bedgraph > As.State3_regions.bed
```
but the State3_regions.bed is 0.
```
-rw-rw-r--. 1 qiaowei qiaowei 157M Oct  6 21:34 As.State0_regions.bed
-rw-rw-r--. 1 qiaowei qiaowei 159M Oct  6 21:33 As.State1_regions.bed
-rw-rw-r--. 1 qiaowei qiaowei 321K Oct  6 21:32 As.State2_regions.bed
-rw-rw-r--. 1 qiaowei qiaowei    0 Oct  6 21:14 As.State3_regions.bed
-rw-rw-r--. 1 qiaowei qiaowei 1.7K Oct  6 18:16 As.log
-rw-rw-r--. 1 qiaowei qiaowei 140K Oct  6 18:16 As_peaks.gappedPeak
-rw-rw-r--. 1 qiaowei qiaowei 316M Oct  6 18:16 As.bedgraph
-rw-rw-r--. 1 qiaowei qiaowei  51K Oct  6 18:16 As_summits.bed
-rw-rw-r--. 1 qiaowei qiaowei 1.4K Oct  5 19:17 As.model
-rw-rw-r--. 1 qiaowei qiaowei  26K Oct  5 18:48 As_training.bed
-rw-rw-r--. 1 qiaowei qiaowei 2.4M Oct  5 13:07 As.sorted.bam.bai
-rw-rw-r--. 1 qiaowei qiaowei 5.4G Oct  5 12:35 As.sorted.bam
```

I just want to know if it means there is no open region and my data quality is so poor? Besides, how can I know my data quality and how to trim the data in order to obtain some open region data in HMMRATAC?
Another thing is I have not add `-e blacklist.bed` for some install problem which I haven't fixed now this time.Does the poor quality is caused by blacklist? And I also read https://github.com/LiuLabUB/HMMRATAC/issues/23,maybe after I solved blacklist install problem I can have a test.
Thank you so much for any help.

**Comment by EvanTarbell** [comment]
Since the first release of HMMRATAC, we have switched from a 4 state model to a 3 state model.  So it's actually As.State2_regions.bed that contains the open region (center state).

**Comment by qiaowei-vvjoe** [comment]
ok, thank you so much for your quick reply.
I think I need to know more basic principle about this tool for the following analysis.
Could you please not close this issue now?maybe I need to discuss this result with my PI.

**Comment by EvanTarbell** [comment]
OK will do. As one sidenote, i should point out that the bedgraph file contains all state annotations that were made in the genome. What you will notice is that the number of E2 states will not equal the number of peaks in the gappedPeak file.  This is due to several post annotation filters that are applied before a peak is called.  Therefore your As.State2_regions.bed file might contain regions that we wouldn't consider a "peak", such as ones that are too small etc.

**Comment by LewisKristy** [comment]
what does E0 correspond to now in the 3 state model then?

**Comment by EvanTarbell** [comment]
The states are numbered beginning with zero. So state 0 is the "background" state, state 1 is the "nucleosome" state and state 2 is the "center" state.
