### ISSUE TITLE
Q: normalization of read depth

### ISSUE THREAD

**Issue by shanzhyang** [LiuLabUB/HMMRATAC#38]
Hi,
I'm new to this type of analysis. I compared the ENCODE pipeline and this one on bulk seq data of hES cells. Encode one gave peaks on NANOG and POU5F1 which are kind of expected but HMMRATAC didn't on both genes. I'm wondering if this is caused by the low read depth (66510354 reads) of the data. Or should i lower the stringency? Thanks!

Best,
Shanzheng

**Comment by EvanTarbell** [comment]
I would try lowering the stringency. You can lower the reporting threshold with the --threshold option. It is currently set to 30, lowering it to 10 or 20 might allow those particular peaks to be identified.  I dont think the read depth is an issue. 66M reads is quite good for ATAC-seq.

**Comment by shanzhyang** [comment]
Thank you! I'm going to try it. I just noticed you have added cpm normalization.

**Comment by shanzhyang** [comment]
It helped by setting the threshold to 20. The peaks now look similar to the ones by encode pipeline. Thanks!

**Comment by EvanTarbell** [comment]
Sounds good. Happy to help.
