### ISSUE TITLE
Q: On the Opdf values in the log file

### ISSUE THREAD

**Issue by juhomon** [LiuLabUB/HMMRATAC#44]
Hi,

I've been working with HMMRATAC to identify summits for downstream analysis but I'm somewhat unsure of some of the values describing the model.

In the examples that I found scattered in the issue section and examples I noticed that the Opdf values from my runs are lower (<1)  than the values that others are getting.  I started off with higher -l and -u values for "a safe bet" and running currently with lower -u and -l values (10,5 and 20,10 respectively) and experiencing the same thing. The values get higher by the state so in this sense they are in line with the expected outcome of a good model but I just want to be sure before continuing downstream. 

Is this normal and how would one interpret these values in question? I attached a log file from one of the peak calling runs below. Thank you in advance!

Contents of the log file with retracted filenames.
Version:	1.2.9
Arguments Used:
--bam	< .bam file >
--index	< .bai file >
--genome	< genome size file >
--means	75,200,400,600
--minmapq	30
--upper	40
--lower	20
--output	< outprefix >
--bedgraph	True
--bgscore	True
Fragment Expectation Maximum Done
Mean	75.0	StdDevs	20.0
Mean	182.55893183563134	StdDevs	42.994465842745974
Mean	365.96938542104164	StdDevs	52.02589220132546
Mean	566.0401496018148	StdDevs	73.1375099614439
ScalingFactor	80.065888
Training Regions found and Zscore regions for exclusion found
Training Fragment Pileup completed
Kmeans Model:
HMM with 3 state(s)

State 0
  Pi: 0.3333333333333333
  Aij: 0.333 0.333 0.333
  Opdf: Multi-variate Gaussian distribution --- Mean: [ 0.06 0.103 0.082 0.055 ]

State 1
  Pi: 0.3333333333333333
  Aij: 0.333 0.333 0.333
  Opdf: Multi-variate Gaussian distribution --- Mean: [ 0.18 0.297 0.319 0.251 ]

State 2
  Pi: 0.3333333333333333
  Aij: 0.333 0.333 0.333
  Opdf: Multi-variate Gaussian distribution --- Mean: [ 0.464 0.723 0.75 0.571 ]

Model created and refined. See < outprefix >.model
Model:
HMM with 3 state(s)

State 0
  Pi: 0.3333333333333333
  Aij: 0.973 0.027 0
  Opdf: Multi-variate Gaussian distribution --- Mean: [ 0.037 0.086 0.071 0.043 ]

State 1
  Pi: 0.3333333333333333
  Aij: 0.03 0.963 0.008
  Opdf: Multi-variate Gaussian distribution --- Mean: [ 0.127 0.208 0.203 0.159 ]

State 2
  Pi: 0.3333333333333333
  Aij: 0 0.021 0.979
  Opdf: Multi-variate Gaussian distribution --- Mean: [ 0.352 0.51 0.531 0.411 ]

Genome split and subtracted masked regions
0 round viterbi done
50 round viterbi done
100 round viterbi done
131 round viterbi done
Total time (seconds)= 	33066

**Comment by EvanTarbell** [comment]
Everything looks fine to me. It could simply be a matter that you have fewer/more reads than other datasets that other people have generated. Also keep in mind that the version you are using uses a CPM normalization of the signal tracks, so some other examples may not have had that feature yet, hence higher values. Overall, it looks fine. Everything came out the way i would expect it to.

**Comment by juhomon** [comment]
Thanks for the confirmation, this peak caller is just what I've been looking for!
