### ISSUE TITLE
Does HMMRATAC still work when BAM reads have been stripped of sequence and base qualities such as that produced by deepTools alignmentSieve?

### ISSUE THREAD

**Issue by EvanTarbell** [LiuLabUB/HMMRATAC#47]
Does HMMRATAC still work when BAM reads have been stripped of sequence and base qualities such as that produced by deepTools alignmentSieve?

_Originally posted by @jeffhsu3 in https://github.com/LiuLabUB/HMMRATAC/issues/46#issuecomment-580270193_

**Comment by EvanTarbell** [comment]
What options did you use for filtering the reads? From what i can tell, the alignmentSieve filters are similar to the filters already existed in HMMRATAC. Depending on what you are trying to do could make the step redundant.

**Comment by jeffhsu3** [comment]
Just the --ATACshift option.

**Comment by EvanTarbell** [comment]
If that is the case, you can refer to #46, in which the previous user was able to perform the shift using AtacQC, which shifted the reads while maintaining the other aspects of the read information so as to not conflict with the samtools reader in HMMRATAC. Additionally, i can refer you to #21, in which i state that the read shift isnt necessary with HMMRATAC, because of the 10bp resolution that HMMRATAC works with, as well as the fact that the shift will only be necessary for footprinting, not so much for peak-calling

**Comment by jeffhsu3** [comment]
Thanks for the response!

**Comment by margauxhaering** [comment]
Hi, sorry to bother. 
I had the same error than @jeffhsu3 commented on #46, but none of these answers solved my problem... 
I have been looking for adjusting chromosome names as suggested but it was ok.. 
To refer, I also used deepTools' alignmentSieve. 
My global error is : 

`Exception in thread "main" net.sf.samtools.SAMFormatException: SAM validation error: ERROR: Record 1, Read name K00201:414:HGKJFBBXY:2:1103:14976:12638, Zero-length read without FZ, CS or CQ tag
	at net.sf.samtools.SAMUtils.processValidationErrors(SAMUtils.java:448)
	at net.sf.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:541)
	at net.sf.samtools.BAMFileReader$BAMFileIndexIterator.<init>(BAMFileReader.java:648)
	at net.sf.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:598)
	at net.sf.samtools.BAMFileReader.query(BAMFileReader.java:352)
	at net.sf.samtools.SAMFileReader.query(SAMFileReader.java:363)
	at HMMR_ATAC.pullLargeLengths.read(pullLargeLengths.java:112)
	at HMMR_ATAC.pullLargeLengths.<init>(pullLargeLengths.java:61)
	at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:219)`

Thank you
