### ISSUE TITLE
FR: Removing chrM

### ISSUE THREAD

**Issue by hisplan** [LiuLabUB/HMMRATAC#50]
**Is your feature request related to a problem? Please describe.**
Does HMMRATAC provide an easy way to remove `chrM`?

**Describe the solution you'd like**
A new parameter to remove a list of chromosomes:
e.g. `--exclude chrM,GL` (comma-separated)

**Describe alternatives you've considered**
- Supply a chrM bed file to `--blacklist`
- Run `awk` to remove `chrM` or `M`

**Comment by EvanTarbell** [comment]
If you remove those chromosomes from the genome file given in the -g or --genome option, then those chromosomes wont be used at any stage of the algorithm. Providing those chromosomes in the --blacklist option will prevent them from being called or used in the model creation/annotation step, but they may still be used to calculate the fragment distribution parameters or to calculate the genome stats (mean, and therefore fold change etc).

**Comment by hisplan** [comment]
Thanks!
