### ISSUE TITLE
How to run HMMRATAC in conda environment?

### ISSUE THREAD

**Issue by liangcmu** [LiuLabUB/HMMRATAC#54]
I have install HMMRATAC in conda environment by issuing the following command:

conda install hmmratac

Next, what command should I issue to initiate the HMMRATAC program? 

In your quick start document, you have following suggestion:

java -jar HMMRATAC_V1.2.4_exe.jar -b ATACseq.sorted.bam -i ATACseq.sorted.bam.bai -g genome.info

However, this does not work with conda environment.  What should I do?

**Comment by EvanTarbell** [comment]
I have never actually run HMMRATAC with conda (it was put there by someone else). But according to issue #48 , the command used was:
HMMRATAC -b bamFile -i indexFile -g genomeFile

**Comment by El-Castor** [comment]
Hi @liangcmu, 

HMMATAC is avaible on bioconda channel at the version 1.10.2
