### ISSUE TITLE
Q: Average runtime for HMMRATAC?

### ISSUE THREAD

**Issue by blin100** [LiuLabUB/HMMRATAC#56]
Hi all, I'm curious what peoples runtimes for HMMRATAC are? I'm attempting to run it on a bam file of 120M reads, and it's going over 8 hours to process this. The logfile shows this:

```
Version:	1.2.10
Arguments Used:
-b	/mapped/BL1_BT2Mapped_sortedByCoord.bam
-i	/mapped/BL1_BT2Mapped_sortedByCoord.bam.bai
-g	/mapped/genome.info
-o	BL1_
Fragment Expectation Maximum Done
Mean	50.0	StdDevs	20.0
Mean	157.2458166830402	StdDevs	40.21108207834556
Mean	354.25560135136556	StdDevs	79.90782467930424
Mean	712.4633651541315	StdDevs	119.6223917776196
```

This was done on a single core (I assume it's still singlethreaded since no patch notes have said otherwise) with 32 gigs of ram.

I only saw one flag (-f) that would reduce runtime, but that seemed rather detrimental and not recommended for the first few runs I'm doing. I'm curious what is the expected runtime, as I'm doing this on a cluster and would like to have a better estimate than just doubling the time allocation each time this fails :D 

Thanks in advance!

**Comment by EvanTarbell** [comment]
Is that the whole log file? Or just the beginning of it?

**Comment by blin100** [comment]
That's unfortunately the whole log file after 8 hours of running, slurm killed it afterwards. I'm rerunning it now with 16 hours runtime.
I'm very unfamiliar with your tool, any idea roughly of how far it had gotten in that time?

Thanks very much!

**Comment by EvanTarbell** [comment]
It got through the fragment EM part, which is designed to determine the optimal parameters for the mixture model used to create the separated ATAC-seq signal tracks (nucleosome free vs nuclesosome enriched). When we benchmarked the algorithm, we used 80M read datasets and the runtime averaged ~5.5 hours. The fragment EM is probably the single longest task that is done. 16 hours should be enough to have it completely run. However, considering you already have the fragment EM parameters, what you could do is re-run using the following options:
`-f false -m 50.0,157.25,354.26,712.46 -s 20.0,40.21,79.91,119.62`
This will prevent the EM step from being performed and will use the means and standard deviations that you already found. This should considerably reduced the runtime.

**Comment by blin100** [comment]
Ahh, I understand now, that's very helpful. Thanks very much! Once both the complete run and the amended run are done, I'll paste the runtimes here for future benchmarks.

**Comment by EvanTarbell** [comment]
Sounds good!! Happy to help!

**Comment by blin100** [comment]
Just to close this out, I was finally able to run this (120M reads) using the fragment EM parameters:
```
Cores: 1
CPU Utilized: 16-23:08:52
CPU Efficiency: 9885.56% of 04:07:07 core-walltime
Job Wall-clock time: 04:07:07
Memory Utilized: 94.87 GB
Memory Efficiency: 48.57% of 195.31 GB
```

In contrast, a smaller input (26M reads) took 5 hours to run from start to finish:
```
Cores: 1
CPU Utilized: 22-00:01:39
CPU Efficiency: 9964.87% of 05:17:56 core-walltime
Job Wall-clock time: 05:17:56
Memory Utilized: 35.31 GB
Memory Efficiency: 75.32% of 46.88 GB
```
