### ISSUE TITLE
BR: Java.lang.OutOfMemoryError, reducing window does not solve

### ISSUE THREAD

**Issue by blin100** [LiuLabUB/HMMRATAC#57]
Hi, I'm running into a curious problem with HMMRATAC, running on the cluster.
I'm using a single thread, with 48 gb of ram requested, with java/jdk-1.8u112 loaded. The command I'm running is:

java -jar/HMMRATAC_V1.2.10_exe.jar -f false -m 50.0,157.25,354.26,712.46 -s 20.0,40.21,79.91,119.62 --window 2500000 -b mapped/BL1_BT2Mapped_sortedByCoord.bam -i /mapped/BL1_BT2Mapped_sortedByCoord.bam.bai -g /BL_ATAC/mapped/genome.info -o BL1_prerun_

Just under 4 hours of running, the error I get is:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at FormatConverters.PileupToBedGraph.generateGraph2(PileupToBedGraph.java:88)
	at FormatConverters.PileupToBedGraph.run(PileupToBedGraph.java:53)
	at FormatConverters.PileupToBedGraph.<init>(PileupToBedGraph.java:41)
	at WigMath.pileup.toBedGraph(pileup.java:217)
	at WigMath.pileup.build(pileup.java:206)
	at WigMath.pileup.<init>(pileup.java:71)
	at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:270)

```

However, the ram usage is fine:
```
Cores: 1
CPU Utilized: 15-13:36:01
CPU Efficiency: 9975.24% of 03:44:43 core-walltime
Job Wall-clock time: 03:44:43
Memory Utilized: 30.23 GB
Memory Efficiency: 64.50% of 46.88 GB
```

I originally ran this with the default --window, then dropped it to 5 mb, and now to 2.5 mb and still have the same problem. Do you have any suggestions for how to get this to complete?

Thanks very much!
Brian

**Comment by EvanTarbell** [comment]
It might have something to do with how much memory the java runtime environment has allocated. Try java -Xmx 46G -jar HMMRATAC_V1.2.10_exe.jar etc etc

**Comment by blin100** [comment]
Aha, yes, that's gotta be it. On my cluster, the command: 
`java -XX:+PrintFlagsFinal -version | grep HeapSize`
yields:
```
 uintx ErgoHeapSizeLimit                         = 0                                   {product}
    uintx HeapSizePerGCThread                       = 87241520                            {product}
    uintx InitialHeapSize                          := 262144000                           {product}
    uintx LargePageHeapSizeThreshold                = 134217728                           {product}
    uintx MaxHeapSize                              := 4162846720                          {product}
```
I'll report back in the 4 or so hours it takes to run this thing :D 
Thanks for your very responsive help, I appreciate it!

**Comment by EvanTarbell** [comment]
No problem, happy to help!!

**Comment by blin100** [comment]
ahahaha, one note to any others who run into this problem, you can't have a space between -Xmx and the size allocation. I had to run:
java -Xmx46G -jar HMMRATAC_V1.2.10_exe.jar......

**Comment by blin100** [comment]
Hmmm, I'm sorry this is being so troublesome... it still errored with the same primary error of OutOfMemory:Java Heap space, the details seem slightly different though, but not sure if it's anything particularly significant. Any ideas?

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.toArray(ArrayList.java:376)
	at java.util.ArrayList.addAll(ArrayList.java:577)
	at FormatConverters.PileupToBedGraph.run(PileupToBedGraph.java:53)
	at FormatConverters.PileupToBedGraph.<init>(PileupToBedGraph.java:41)
	at WigMath.pileup.toBedGraph(pileup.java:217)
	at WigMath.pileup.build(pileup.java:206)
	at WigMath.pileup.<init>(pileup.java:71)
	at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:270)
```
The command I ran was:
java -Xmx46G -jar  /HMMRATAC_V1.2.10_exe.jar -f false -m 50.0,157.25,354.26,712.46 -s 20.0,40.21,79.91,119.62 --window 5000000 -b /mapped/BL1_BT2Mapped_sortedByCoord.bam -i /mapped/BL1_BT2Mapped_sortedByCoord.bam.bai -g /mapped/genome.info -o BL1_prerun_

There's no errors saying the -Xmx didn't work, but I'm unsure of how to test this in reality, as it seems what I can find, such as jps -v or jmap -heap all don't seem to be compatible with running this as a cluster job...

Thanks!
Brian

**Comment by EvanTarbell** [comment]
Being a cluster job, its possible that the individual user isn't allowed to reset the heap space requirements. You might want to check with the system administrator to find out. 

Ill check the code too, to make sure it isnt a memory leak

**Comment by blin100** [comment]
I queried the cluster people about setting heap space requirements. In the meantime, is there any way of me providing you anylog file or temp file that might help out?
Thanks!

**Comment by EvanTarbell** [comment]
sure. you can email it to me if they cant be uploaded here.
evantarbell@gmail

**Comment by blin100** [comment]
Sorry, very much a beginner here, no idea what kind of log files I even *can* send you? The only log I can see is the stderror file I attached earlier that shows it's a java heap size error. Is there another place or a flag I can use to get something more useful?

**Comment by blin100** [comment]
I was able to solve this problem on my end, appears that for a BAM file of 120M reads, I needed 95GB of ram, and to set -Xmx appropriately as well. In my case, I figured better more than keep failing attempts, so I allocated 200 gb of ram, and set -Xmx200G
Clearly that was overkill, but it worked!
