### ISSUE TITLE
Q: In HMMRATAC output - gapped format, we often see blue rectangles with some thin lines, either in the upstream, the downstream, or both of the rectangles.  Sometimes, such thin lines are very long.  Do these thin lines  have special meaning  (e.g., nucleosome positions?)  

### ISSUE THREAD

**Issue by liangcmu** [LiuLabUB/HMMRATAC#59]
**Use case**
A clear and concise description of what the use case is. For example: my data is from [...]

**Describe the problem**
A clear and concise description of what happend.

**Describe the solution you tried**
A clear and concise description of any solutions you've tried.

**Additional context**
Add any other context or screenshots about your use case here.

**Comment by EvanTarbell** [comment]
yes, those lines represent the flanking nucleosome positions. we made the output like that for better visualization on the browsers
