### ISSUE TITLE
BR: Results are not reproducible

### ISSUE THREAD

**Issue by angelosarmen** [LiuLabUB/HMMRATAC#66]
Hi,

Thank you for developing HMMRATAC. I ran HMMRATAC 1.2.10 twice on a cluster for the same set of samples, using `-e wgEncodeDacMapabilityConsensusExcludable.bed` and `--removeDuplicates false` (as duplicates were already removed) in addition to the required arguments. Since the tool uses a random seed (10151 by default, I didn't change it), I was expecting the output to be exactly the same for both runs. This is not the case, however.

For the majority of samples, the number of peaks in *_peaks.gappedPeak is slightly different. I compared the gappedPeak files for one such sample, and found that the boundaries of the shared peaks slightly differ and the names of most peaks differ. The *.model files also differ, although the *_training.bed files are the same. Is there a random component of HMMRATAC other than the choice of training peaks?

For another sample, only "HighCoveragePeak_0" peaks were present in *_peaks.gappedPeak and sample_summits.bed was empty in the second run (high coverage peaks were exactly the same in both runs).

**Comment by EvanTarbell** [comment]
Can you post the first 60 lines of the log files for two of your runs? Runs on the same dataset with the same parameters. Can you also let me know how many peaks were in each gappedPeak file? And can you also post the first 60 lines of the log file for the sample that didnt produce any peaks?

**Comment by angelosarmen** [comment]
Here you go. The two samples are the ones I mentioned above (sample 1 has subtle differences in the peaks, sample 2 only generated high-coverage peaks in the 2nd run).

[sample_1_run_1.log](https://github.com/LiuLabUB/HMMRATAC/files/4904657/sample_1_run_1.log)
[sample_1_run_2.log](https://github.com/LiuLabUB/HMMRATAC/files/4904658/sample_1_run_2.log)

[sample_2_run_1.log](https://github.com/LiuLabUB/HMMRATAC/files/4904659/sample_2_run_1.log)
[sample_2_run_2.log](https://github.com/LiuLabUB/HMMRATAC/files/4904660/sample_2_run_2.log)

Peak counts:

Sample 1 run 1: 26697
Sample 1 run 2: 26699

Sample 2 run 1: 8023
Sample 2 run 2: 573

**Comment by EvanTarbell** [comment]
You are right that there are other times where randomization occur, and they appear to be playing a role in the differences you are seeing. For instance, in sample 1, there are slight differences in the fragment EM parameters, which then are likely responsible for the small differences you are seeing. My guess is that these differences are very minor, and you can confirm that with something like `bedtools jaccard`. 
The fragment EM issue, and other randomization issues, are also occurring with sample 2, but there is a bigger issue. What is happening is related to points 3 and 5 in the troubleshooting section of the User guide. Setting a higher value for the -u and -l options will produce a more stable model across runs. Considering the lower depth and the fewer number of reads in the run #2, you might also want to consider lowering the --threshold option.
I will work on adding the seed to the other randomized portions of the code, to eliminate the issues related to sample 1. The differences are likely minimal anyway, and that can be confirmed with a jaccard analysis. In the meantime, use more stringent settings for -u and -l for sample 2, and the differences between runs should be more akin to the differences with sample 1

**Comment by angelosarmen** [comment]
Thank you. I'm not sure how to determine the samples for which I should use more stringent settings, however. I considered doing what you did in the paper:

> Additionally, for two monocyte samples (accession numbers GSM2325689 – RPMI 4h and GSM2325681 – BG d1) HMMRATAC did not produce a typical model with the default settings (-u 20 –l 10). The ideal model should show the highest NFR, 1Ns, 2Ns and 3Ns signals in the third (center) state and the second highest values of all four signals in the second (nucleosome) state. In this case, we found that the second state (nucleosome) had the highest NFR signal while the third (center) state had the highest 1Ns, 2Ns and 3Ns signals.

I observe the same thing in most of my low-depth samples (including sample 2 run 2 above) but not all of them. Maybe I should set a fixed threshold on the number of reads (I'm currently using a data-dependent one), but again, I'm not sure how to choose it.

Regarding the seeds, are you planning to add them soon? Another feature would be to check for the above problem with the states automatically and inform the user if present.

**Comment by EvanTarbell** [comment]
Yes, what is written in the paper is the same points being made in the troubleshooting section of the user guide. 
And if there are other examples of different numbers of peaks, can you share those log files and peak counts as well?

**Comment by angelosarmen** [comment]
Sure, this is the sample with the largest absolute difference in the number of peaks across runs:

[sample_3_run_1.log](https://github.com/LiuLabUB/HMMRATAC/files/4924905/sample_3_run_1.log)
[sample_3_run_2.log](https://github.com/LiuLabUB/HMMRATAC/files/4924906/sample_3_run_2.log)

Peak counts:
Sample 3 run 1: 39863
Sample 3 run 2: 16695

The sample has 60M reads and a TSS enrichment 25.

**Comment by EvanTarbell** [comment]
So sample 3 runs into another problem that is mentioned in point 5 of the troubleshooting section of the guide, namely:

> Another possible issue is that the log file shows that the kmeans model is identical to the final model. In the event that Baum Welch training fails, HMMRATAC will use the original Kmeans model in order to produce some result. Because the kmeans model doesn't include transition parameters, this is also not ideal. The way to solve this issue, is the same as above, namely setting mote stringent parameters to create more separation in the values between states.

What happened here is that with one one (run 1) the Baum Welch process did work while in run 2 it didn't. Although adding a seed would help here, it could end up making each run more like run 1 or more like run 2. Either way, you will still need to change the -u and -l parameters. Doing so will make these samples as similar as your sample 1, in terms of similarity. 

I will add to my to do list adding the seeds to the other randomized processes as well as adding some message in the log file in the event that the model is less than ideal. I cant say when ill have a new release with those fixes, as I am quite busy right now and those additions are pretty minor. In the meantime (and regardless of whether the additions are in or not) you should change the -u and -l parameters for samples 2 and 3. This will make the results for those samples extremely robust across runs

**Comment by angelosarmen** [comment]
Thanks, I didn't notice!

I decided to run _all_ samples with -u 40 –l 20 (would you recommend this?), run them again, and confirm that the differences are minor between the two runs.

**Comment by EvanTarbell** [comment]
Absolutely, that sounds fine.  And based on the experience you had with two of your three runs, it seems completely appropriate to me.

**Comment by angelosarmen** [comment]
I ran bedtools jaccard and there are major differences across runs for a few samples only, so there is probably no need to use the stringent parameters for all samples.

Can you please tell me what the high coverage peaks (peaks named HighCoveragePeak_0) are. I suspected that they are the blacklist regions but actually they're a superset of them. Why are the blacklisted regions included in the output and what are the rest high coverage peaks?

Also just to confirm, do mitochondrial reads need to be removed beforehand or will HMMRATAC remove them anyway?

**Comment by EvanTarbell** [comment]
No, HMMRATAC doesn't remove mitochondrial reads. So you should remove them beforehand. Alternatively if you don't have a chrM line in the genome file, then any reads mapping to the mito wont be used for any process, including model building or genome annotation.
