### ISSUE TITLE
-k option disagreement between help and userguide

### ISSUE THREAD

**Issue by mcjmigdal** [LiuLabUB/HMMRATAC#7]
found this disagreement between userguide and help message.
User guide:
-k , --kmeans <int> Number of states in the model. Default is 4.
help message:
-k , --kmeans <int> Number of States in the model. Default = 3.

**Comment by EvanTarbell** [comment]
I apologize for the misunderstanding.  The default IS 3, the help message is correct. The user guide has not been updated. I will correct this issue. Thanks
