### ISSUE TITLE
Q: What does the third number in 12th column of gappedPeak output file mean?

### ISSUE THREAD

**Issue by SichongP** [LiuLabUB/HMMRATAC#71]
Version of program: 

hmmratac=1.2.9=0 from bioconda channel

Hi,

I wasn't able to find answer to this question online so I'm hoping that you could help me with this. Below is an example of my output:

> chr21   206160  207980  Peak_2  .       .       206620  206920  255,0,0 3       1,300,1 0,460,1819      5.983718123324219       -1      -1
> chr21   221720  223760  Peak_3  .       .       222460  223290  255,0,0 3       1,830,1 0,740,2039      6.655547812317911       -1      -1

So in the first line the 12th column, 460 as I understand refers to the start of open state, which matches 2nd and 7th columns (206620-206160=460). However, I'm having trouble understanding the next number (1819). It seems to be near the end of the peak (206160+1819=207979), only 1bp from the end. According to the guide in this repo, this seems to mean that the 3rd region, which is the downstream nucleosome region, starts at 207979 and is only 1bp long?

This seems to be the case for most of the peaks, if not all. Does this indicate a problem with my model since flanking nucleosome regions surely shouldn't be 1bp long, or am I misunderstanding something?

Thank you

**Comment by EvanTarbell** [comment]
You are correct that the value represents the start of the third block. And yes, you are correct that this has a length of one. This was done for visualization purposes when the peaks were imported into a genome browser. 
In reality the flanking nucleosomes are simply anything in the peak that is not the center state. so nucleosome 1 (for peak 2) is
chr21 206160 206620
and nucleosome 2 is
chr21 206920 207980

**Comment by SichongP** [comment]
Thank you for that explanation. That was very helpful!
