### ISSUE TITLE
Q: Duplicate-read removal

### ISSUE THREAD

**Issue by angelosarmen** [LiuLabUB/HMMRATAC#72]
Hi,

Does HMMRATAC remove reads marked as duplicates in the BAM file or does it detect duplicates on its own? The paper seems to indicate the latter:

> Reads that had a mapping quality score <30 or that were considered duplicates (exact same start and stop position) were removed from the merged files

**Comment by EvanTarbell** [comment]
Sorry for the confusion. It is the former actually. HMMRATAC removes reads that have been MARKED as duplicate.

**Comment by angelosarmen** [comment]
Thank you for the prompt reply!
