### ISSUE TITLE
Q: Determining -m and -s parameters

### ISSUE THREAD

**Issue by czfoo** [LiuLabUB/HMMRATAC#77]
Dear Sir/Madam

According to your readme, the default values for these parameters were designed for human genomes, and they should be adjusted for non-human genomes. In that case, how would you recommend calculating those values? For instance, in may case, my data came from mouse tissue, so how should I adjust those values for the mouse genome?

Thank you.

**Comment by EvanTarbell** [comment]
I think those values will be ok, so long as you fit the data to it. IE. don't set -f false. The default values are estimated to fitted values based on your data. so although the mononucleosome is ~200bp to start, that will typically be fitted to a different value.
