### ISSUE TITLE
HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:489)

### ISSUE THREAD

**Issue by Lucas446** [LiuLabUB/HMMRATAC#9]
Hi, 

Thanks for your recent update.

I tried to run the code using the following command:

java -jar /Applications/bioinfo_tools/HMMRATAC-master/HMMRATAC_V1.2.1_exe.jar
-b BAM_FILE.bam -i BAM_FILE.bam.bai -g dm6.genome --bedgraph true --bgscore true -o file_hmmratac

After several minutes it started to print:
chr3L	16828	26916	training
chr3L	16917	26920	training
chr3L	16922	26931	training
chr3L	16932	26939	training
chr3L	16940	26957	training
....

And then an error message:
**Exception in thread "main" java.lang.NullPointerException
	at HMMR_ATAC.Main_HMMR_Driver.main(Main_HMMR_Driver.java:489)**

it generated 2 non empty files: file_hmmratac.log & file_hmmratac.model

Do you have any idea of the problem here ?

Version of JAVA:
$java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

Version of samtools 1.9 (using htslib 1.9)

Thank you very much for your help,

**Comment by EvanTarbell** [comment]
I just published version 1.2.2 which should take care of this problem. Let me know if it works.

**Comment by EvanTarbell** [comment]
Sorry it looks like 1.2.2 has another bug. When i fix the first, it created a second. Im testing a new release that should solve the issue once and for all. I will post it soon.

**Comment by EvanTarbell** [comment]
OK V1.2.3 should take care of this. let me knoe if it works
